default:
  tags:
    - docker
  # Image from https://hub.docker.com/_/gcc/ based on Debian
  image: gcc:9

# Make sure commits are GPG signed
ci-fairy:
  stage: test
  script:
    - apt update
    - apt install -y python3-pip git
    - PIP_BREAK_SYSTEM_PACKAGES=1 pip3 install git+https://gitlab.freedesktop.org/freedesktop/ci-templates@7811ba9814a3bad379377241c6c6b62d78b20eac
    - echo Checking commits $CI_FAIRY_BASE_COMMIT..HEAD
    - ci-fairy check-commits --gpg-signed-commit $CI_FAIRY_BASE_COMMIT..HEAD
  tags:
    - 'docker'
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        CI_FAIRY_BASE_COMMIT: $CI_MERGE_REQUEST_DIFF_BASE_SHA
    - if: $CI_PIPELINE_SOURCE != "merge_request_event"
      variables:
        CI_FAIRY_BASE_COMMIT: 'HEAD^1'

.autoconf:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y libfftw3-dev
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS}
    - make
    - make check

autoconf:
  extends: .autoconf
  script:
    - ./autogen.sh
    - ./configure ${CONFIG_FLAGS}
    - make
    - make distcheck

fixed-point:
  extends: .autoconf
  variables:
    CONFIG_FLAGS: --enable-fixed-point

no-float:
  extends: .autoconf
  variables:
    CONFIG_FLAGS: --enable-fixed-point --disable-float-api

no-examples:
  extends: .autoconf
  variables:
    CONFIG_FLAGS: --disable-examples

.cmake:
  stage: build
  before_script:
    - apt-get update &&
      apt-get install -y cmake
  script:
    - cmake -S . -B build ${CMAKE_FLAGS}
    - cmake --build build

cmake:
  extends: .cmake

cmake-fixed-point:
  extends: .cmake
  variables:
    CMAKE_FLAGS: -DUSE_FIXED_POINT=ON

cmake-shared:
  extends: .cmake
  variables:
    CMAKE_FLAGS: -DBUILD_SHARED_LIBS=ON
